server:
    port: 9191

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: demo-cqrs
      repositories:
        type: auto
  # rabbit mq
  rabbitmq:
     host: localhost
     port: 15672
     username: guest
     password: guest




# Axon
axon:
  amqp:
    exchange: axonevents
    transaction-mode: PUBLISHER_ACK


#Swagger
swagger:
  host: localhost:9191
  relativePath:
